name: Publish NuGet and GitHub Package

on:
  push:
    branches:
      - nuget

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Get Current Version
        id: get_current_version
        run: |
          CURRENT_VERSION=$(grep -oP '(?<=<Version>).*?(?=</Version>)' src/YG.ASPNetCore.FileManager/YG.ASPNetCore.FileManager.csproj)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Fetch Remote Tags
        run: git fetch --tags

      - name: Check if Tag Exists Remotely
        id: check_tag
        run: |
          REMOTE_TAG_EXISTS=$(git ls-remote --tags origin | grep -w "refs/tags/${{ env.CURRENT_VERSION }}" || true)
          if [ -n "$REMOTE_TAG_EXISTS" ]; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Increment Version if Tag Exists
        id: increment_version
        run: |
          if [ "${{ env.TAG_EXISTS }}" == "true" ]; then
            # Increment the patch version
            IFS='.' read -r MAJOR MINOR PATCH <<< "${{ env.CURRENT_VERSION }}"
            NEW_PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
            sed -i "s|<Version>${{ env.CURRENT_VERSION }}</Version>|<Version>$NEW_VERSION</Version>|" src/YG.ASPNetCore.FileManager/YG.ASPNetCore.FileManager.csproj
            echo "FINAL_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          else
            echo "FINAL_VERSION=${{ env.CURRENT_VERSION }}" >> $GITHUB_ENV
          fi

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit changes if the version has been updated
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am "Prepare release ${{ env.FINAL_VERSION }}"
          fi

      - name: Create and Push Tag
        run: |
          # Verify tag existence again before creating and pushing
          if git ls-remote --tags origin | grep -q "refs/tags/${{ env.FINAL_VERSION }}"; then
            echo "Tag ${{ env.FINAL_VERSION }} already exists. Skipping creation."
          else
            git tag "${{ env.FINAL_VERSION }}"
            git push origin "${{ env.FINAL_VERSION }}"
          fi

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --output ./output

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./output/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet nuget push ./output/*.nupkg -s "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -k $GITHUB_TOKEN
